# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
from pathlib import Path

# Add python modules to be documented
config_file_dir = os.path.dirname(__file__)
project_root =  os.path.abspath( os.path.join( config_file_dir, '..' ) )
src_dir = os.path.abspath( os.path.join( project_root, 'src' ) )

sys.path.insert( 0,  project_root)
sys.path.insert( 0, src_dir )

# -- Project information -----------------------------------------------------

project = u'pyWellSFM - Python Well Stratigraphic Forward Modelling'
copyright = u'2026 Martin Lemay <martin.lemay@mines-paris.org>'
author = u'Martin Lemay'

# The short X.Y version
version = u'1.0'
# The full version, including alpha/beta/rc tags
release = u'0'

# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx_design', 'sphinx.ext.todo', 'sphinx.ext.autodoc', 'sphinx.ext.doctest', 
    'sphinx.ext.mathjax', 'sphinxarg.ext', 'sphinx.ext.napoleon', 'sphinx.ext.autosummary', 
    'sphinxcontrib.programoutput'
]

#autodoc_mock_imports = [ "pybend", ]
autoclass_content = 'both'
autodoc_default_options = {
    'members': True,
    'member-order': 'groupwise',
    'private-members' : True,
    'undoc-members': True,
    'exclude-members': '__weakref__',
    'show-inheritance': True,
}

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = [ u'_build', 'Thumbs.db', '.DS_Store', 'cmake/*' ]

todo_include_todos = True

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# -- Theme options ----------------------------------------------
extensions += [
    'sphinx_rtd_theme',
]

html_theme = "sphinx_rtd_theme"

html_theme_options = { 'navigation_depth': -1, 'collapse_navigation': False }

html_static_path = [ './_static' ]

# Copy extra non-source files directly into the built HTML output.
# This lets us link to downloadable notebooks without copying them into `docs/`.
html_extra_path = [
    str(Path(project_root) / "notebooks"),
]

html_css_files = [
    'theme_overrides.css',
]

# -- Options for HTMLHelp output ---------------------------------------------
# Output file base name for HTML help builder.
htmlhelp_basename = 'pyWellSFMDoc'