# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import shutil
import sys
import tomllib
from pathlib import Path

# Add python modules to be documented
config_file_dir = os.path.dirname(__file__)
project_root =  os.path.abspath( os.path.join( config_file_dir, '..' ) )
src_dir = os.path.abspath( os.path.join( project_root, 'src' ) )

sys.path.insert( 0,  project_root)
sys.path.insert( 0, src_dir )

# -- Project information -----------------------------------------------------

project = u'pyWellSFM - Python Well Stratigraphic Forward Modelling'
copyright = u'2026 Martin Lemay <martinlemay@mines-paris.org>'
author = u'Martin Lemay'

# The full version, read from pyproject.toml (single source of truth)
with open(os.path.join(project_root, 'pyproject.toml'), 'rb') as f:
    release = tomllib.load(f)['project']['version']
# The short X.Y version
version = '.'.join(release.split('.')[:2])

# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx_design', 'sphinx.ext.todo', 'sphinx.ext.autodoc', 'sphinx.ext.doctest',
    'sphinx.ext.mathjax', 'sphinxarg.ext', 'sphinx.ext.napoleon', 'sphinx.ext.autosummary',
    'sphinxcontrib.programoutput', 'sphinx.ext.intersphinx', 'myst_nb'
]

# -- Notebooks ---------------------------------------------------------------
# Render the example notebooks with their stored outputs (no execution, so the
# docs build does not need to run the simulations).
nb_execution_mode = 'off'
# Hide stderr (e.g. library warnings), which shows absolute file paths.
nb_output_stderr = 'remove'

# Sphinx only reads sources under docs/, so mirror the notebooks into
# docs/notebooks/ (git-ignored) at each build.
_nb_src_dir = Path(project_root) / 'notebooks'
_nb_dst_dir = Path(config_file_dir) / 'notebooks'
_nb_dst_dir.mkdir(exist_ok=True)
for _nb in _nb_src_dir.glob('*.ipynb'):
    shutil.copy2(_nb, _nb_dst_dir / _nb.name)

intersphinx_mapping = {
    'pywellsfmui': ('https://pywellsfmui.readthedocs.io/en/latest/', None),
}

#autodoc_mock_imports = [ ]
autoclass_content = 'both'
autodoc_default_options = {
    'members': True,
    'member-order': 'groupwise',
    'private-members' : True,
    'undoc-members': True,
    'exclude-members': '__weakref__',
    'show-inheritance': True,
}

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
# myst_nb registers '.ipynb' (and '.md') on top of this.
source_suffix = {'.rst': 'restructuredtext'}

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = [
    u'_build', 'Thumbs.db', '.DS_Store', 'cmake/*',
    # Markdown notes, not documentation pages (myst_nb parses '.md' files)
    'superpowers', 'depositionalSimulator_context.md',
]

todo_include_todos = True

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# -- Theme options ----------------------------------------------
extensions += [
    'sphinx_rtd_theme',
]

html_theme = "sphinx_rtd_theme"

html_theme_options = { 'navigation_depth': -1, 'collapse_navigation': False }

html_static_path = [ './_static' ]

# Copy extra non-source files directly into the built HTML output.
# This lets us link to downloadable notebooks without copying them into `docs/`.
html_extra_path = [
    str(Path(project_root) / "notebooks"),
]

html_css_files = [
    'theme_overrides.css',
]

# -- Options for HTMLHelp output ---------------------------------------------
# Output file base name for HTML help builder.
htmlhelp_basename = 'pyWellSFMDoc'