"""PyWellSFM public API."""

import logging

from .io import validate_json_file_against_schema
from .model import (
    AccommodationSpaceWellCalculator,
    AccumulationCurve,
    AccumulationModel,
    AccumulationModelElementGaussian,
    AccumulationModelElementOptimum,
    CarbonateOpenRampDepositionalEnvironmentModel,
    CarbonateProtectedRampDepositionalEnvironmentModel,
    Curve,
    DepositionalEnvironment,
    DepositionalEnvironmentModel,
    DepthAgeModel,
    Element,
    EnvironmentalFacies,
    Facies,
    FaciesCriteria,
    FaciesCriteriaCollection,
    FaciesCriteriaType,
    FaciesModel,
    Marker,
    PetrophysicalFacies,
    RealizationData,
    Scenario,
    SedimentaryFacies,
    StratigraphicSurfaceType,
    SubsidenceType,
    UncertaintyCurve,
    Well,
)
from .simulator import (
    DepositionalEnvironmentSimulator,
    DESimulatorParameters,
    EnvironmentConditionSimulator,
    FSSimulator,
    FSSimulatorParameters,
    IntervalDistanceMethod,
)
from .utils.logging_utils import (
    clear_stored_logs,
    configure_logging,
    export_stored_logs,
    export_stored_logs_to_json_file,
    export_stored_logs_to_text_file,
    get_logger,
    get_stored_log_messages,
    get_stored_logs,
    set_log_level,
)

__version__ = "0.0.1"
__all__ = [
    "AccommodationSpaceWellCalculator",
    "AccumulationCurve",
    "AccumulationModel",
    "AccumulationModelElementOptimum",
    "AccumulationModelElementGaussian",
    "CarbonateOpenRampDepositionalEnvironmentModel",
    "CarbonateProtectedRampDepositionalEnvironmentModel",
    "Curve",
    "DepositionalEnvironment",
    "DepositionalEnvironmentModel",
    "DepositionalEnvironmentSimulator",
    "DepthAgeModel",
    "DESimulatorParameters",
    "Element",
    "EnvironmentConditionSimulator",
    "EnvironmentalFacies",
    "Facies",
    "FaciesCriteria",
    "FaciesCriteriaCollection",
    "FaciesCriteriaType",
    "FaciesModel",
    "FSSimulator",
    "FSSimulatorParameters",
    "IntervalDistanceMethod",
    "Marker",
    "PetrophysicalFacies",
    "RealizationData",
    "Scenario",
    "SedimentaryFacies",
    "StratigraphicSurfaceType",
    "SubsidenceType",
    "UncertaintyCurve",
    "Well",
    "clear_stored_logs",
    "configure_logging",
    "export_stored_logs",
    "export_stored_logs_to_json_file",
    "export_stored_logs_to_text_file",
    "get_logger",
    "get_stored_log_messages",
    "get_stored_logs",
    "set_log_level",
    "validate_json_file_against_schema",
]


configure_logging(level=logging.INFO, enable_console=True)
